### ISSUE TITLE
FreeBSD 10 Segmentation fault

### ISSUE THREAD

**Issue by Architector-of-Matrix** [infusion/PHP-Facedetect#12]
After installation when i have include facedetect.so into php.ini and reboot php-fpm:

Starting php_fpm.
Segmentation fault (core dumped)
/usr/local/etc/rc.d/php-fpm: WARNING: failed to start php_fpm

**Comment by infusion** [comment]
Could you please test the current master branch? I rewrote the code almost completely for PHP7 and to come by the old OpenCV C-interface.
