### ISSUE TITLE
Error 500 when trying to detect a face

### ISSUE THREAD

**Issue by Hirbod** [infusion/PHP-Facedetect#13]
Hi,

after some couple of hours I managed to install everything on my Debian Wheezy.
But I receive following error, no matter which cascade I'm trying to load

``` log
OpenCV Error: Unspecified error (The node does not represent a user object (unknown type?)) in cvRead, file /root/opencv-2.4.9/modules/core/src/persistence.cpp, line 4991
terminate called after throwing an instance of 'cv::Exception'
  what():  /root/opencv-2.4.9/modules/core/src/persistence.cpp:4991: error: (-2) The node does not represent a user object (unknown type?) in function cvRead
```

Do you have any idea whats going on? There are hundreds of poeple with this issue but only workarounds for java - not php. Any idea? PHP 5.4 on Debian Wheezy, (fgci)

**Comment by berak** [comment]
since this is using opencv's arcane and no more maintained c-api, only cascade files made from opencv_haartraining (which is also no more available) can be used . cascades made with the recent opencv_traincascade can't be read with cvHaar* functions.

**Comment by infusion** [comment]
Could you guys please test the current master branch? I rewrote the code almost completely for PHP7 and to come by the old OpenCV C-interface.
