### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by loranger** [infusion/PHP-Facedetect#18]
Hello,

I was able to compile this extension for PHP 7 using opencv3 on osx and debian jessie.
I had to

```bash
wget https://github.com/Itseez/opencv/raw/master/modules/objdetect/include/opencv2/objdetect/objdetect_c.h -O /usr/local/include/opencv2/objdetect/objdetect_c.h
```

in order to pass the `./configure` step, and then the facedetect.so compiled, but I cannot use it :

As soon as I try to `face_detect` I get this fatal error :

```
symbol lookup error: /usr/lib/php/20151012/facedetect.so: undefined symbol: MAKE_STD_ZVAL
```

Is this a “normal” bug related to PHP7 and PHP-Facdetect ?

**Comment by sathieu** [comment]
This patch Works-For-Me®: https://github.com/sathieu/PHP-Facedetect/commit/faffe256ccc88aaefe4565ec68d3369ab41e6a16

I'm not able to create a Pull-request for an unknown reason.

**Comment by loranger** [comment]
@sathieu Thank you so much !
I still can't get facedetect to detect any faces, but the extension is now loaded.

I support this PR ! ;)
