### ISSUE TITLE
OpenCV Error: Unspecified error (The node does not represent a user object (unknown type?)) in cvRead

### ISSUE THREAD

**Issue by yiliaofan** [infusion/PHP-Facedetect#19]
OpenCV Error: Unspecified error (The node does not represent a user object (unknown type?)) in cvRead, file /home/work/env/cv/opencv/modules/core/src/persistence.cpp, line 4976
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/work/env/cv/opencv/modules/core/src/persistence.cpp:4976: error: (-2) The node does not represent a user object (unknown type?) in function cvRead

Magick: abort due to signal 6 (SIGABRT) "Abort"...
Aborted

<pre>
test code:

$detect_result = face_detect('./lena512color.jpg', './haarcascade_frontalcatface_extended.xml');
var_dump($detect_result);

</pre>

@TishoTM @weltling @infusion  thanks~!

**Comment by akravchuk** [comment]
The same problem / error. Connected old XML folder haarcascades, and everything works as before

**Comment by binary-data** [comment]
@akravchuk Thanks, I tried xml from opencv 2.4.9 and it worked!

**Comment by sergiomb2** [comment]
@binary-data, Thanks example: http://www.xarg.org/download/facedetect.phps works when I use opencv-2.4.9/data/haarcascades/haarcascade_frontalface_default.xml but not when use opencv-3.1.0/data/haarcascades/haarcascade_frontalface_alt.xml (neither  with opencv-2.4.12.3) see the error:
```
OpenCV Error: Unspecified error (The node does not represent a user object (unknown type?)) in cvRead, file /builddir/build/BUILD/opencv-2.4.12.3/modules/core/src/persistence.cpp, line 5008
terminate called after throwing an instance of 'cv::Exception'
  what():  /builddir/build/BUILD/opencv-2.4.12.3/modules/core/src/persistence.cpp:5008: error: (-2) The node does not represent a user object (unknown type?) in function cvRead

Aborted (core dumped)

```

I have install opencv-2.4.12.3 install on my system , newt step is test with opencv-3.1 on system ...

**Comment by velpaxl** [comment]
Hello, I have the same problem with opencv 2.4.13 and opencv 3.1.0 installed on my Ubuntu 16.04.

The error happens whether I feed to the php function the haarxml file from the 2.4.13 or the 3.1.0 versions.

Here is the error (not matter which file I feed it) :

```
OpenCV Error: Unspecified error (The node does not represent a user object (unknown type?)) in cvRead, file /home/symfony3/opencv-3.1.0/modules/core/src/persistence.cpp, line 4976
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/symfony3/opencv-3.1.0/modules/core/src/persistence.cpp:4976: error: (-2) The node does not represent a user object (unknown type?) in function cvRead

Magick: abort due to signal 6 (SIGABRT) "Abort"...
Aborted (core dumped)
```

Any idea?

**Comment by velpaxl** [comment]
I got the 2.4.9 haar files and it worked, so know I'm gonna get up version by version until it does not work anymore, in order to use the most recent haar files I can.

**Comment by infusion** [comment]
Could you guys please test the current master branch? I rewrote the code almost completely for PHP7 and to come by the old OpenCV C-interface.

**Comment by he44** [comment]
I have the same problem using Python code. Any suggestions?

**Comment by regostar** [comment]
Im getting a similar error
`
<ipython-input-5-0e71cb2b3062> in faceCrop(imagePattern, boxScale)
     78     #   haarcascade_frontalface_default.xml
     79     #   haarcascade_profileface.xml
    `80`     faceCascade = cv.Load('haarcascade_frontalface_alt.xml')
     81 
     82     imgList=glob.glob(imagePattern)

error: The node does not represent a user object (unknown type?)
`

**Comment by sqd918** [comment]
who have the  solution?

**Comment by sergiomb2** [comment]
Update to git master 

https://github.com/infusion/PHP-Facedetect/commit/135c72ace26cd95fd5fd255053bc2eb694d87ad9
