### ISSUE TITLE
PHP Startup: Unable to load dynamic library !

### ISSUE THREAD

**Issue by aymanrb** [infusion/PHP-Facedetect#20]
Whenever I try to restart apache now I get the following error:

```
  PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/facedetect.so' - /usr/lib/php5/20131226/facedetect.so: undefined symbol: cvLoadImage in Unknown on line 0

  PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/facedetect.so' - /usr/lib/php5/20131226/facedetect.so: undefined symbol: cvLoadImage in Unknown on line 0

  AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2e configured -- resuming normal operations
```

An ofcourse it won't work since it wasn't loaded !! Any clue what went wrong ?

PHP Version 5.6.17
OpenCV Verison 3.1.0

**Comment by jammon88** [comment]
I've the same issue!

PHP Version PHP 5.6.19-1
OpenCV Version 3.1.0

**Comment by sergiomb2** [comment]
+1 
facedetect.so: undefined symbol: cvLoadImage, OpenCV Version 3.1.0

**Comment by sergiomb2** [comment]
I found the fix , 
https://pkgs.fedoraproject.org/cgit/rpms/opencv.git/commit/?id=8332955846ff0d567d346b23248561b37eb855f2

we can't compile opencv with -Wl,--as-needed , because seems that clean cvLoadImage symbol ...

**Comment by infusion** [comment]
Could you please send a PR when it's working for you? I don't have time atm to work on it :/

**Comment by sergiomb2** [comment]
The fix is in build of opencv unfortunately ...

**Comment by dfratus** [comment]
Same issue - Installed on Ubuntu 16 latest OpenCV and Facedetected install from source.

**Comment by remicollet** [comment]
Shoudl be fixed by pr #26

**Comment by velpaxl** [comment]
Same issue with PHP7.1 & opencv-3.1.0
Is there a workaround?

**Comment by sergiomb2** [comment]
yes 
https://src.fedoraproject.org/cgit/rpms/php-facedetect.git/tree/php-facedetect-pkgconfig.patch

**Comment by velpaxl** [comment]
Thanks @sergiomb2

**Comment by Meloman-zz** [comment]
Hi,

I have the same issue at service apache2 restart.
I'm on PHP7.0 / Ubuntu 16.4 LTS / OpenCV 3.2

How to apply the @sergiomb2 patch?

Thanks

**Comment by sergiomb2** [comment]
@Meloman-zz , after all we don't need patch opencv , we need patch yes php-facedetect-pkgconfig

https://src.fedoraproject.org/cgit/rpms/php-facedetect.git/tree/php-facedetect-pkgconfig.patch

**Comment by sergiomb2** [comment]
#23 if the problem in stop

**Comment by sergiomb2** [comment]
@Meloman-zz  "retrieve opencv build options from pkg_config #26" was merged .

**Comment by infusion** [comment]
Could you guys please test the current master branch? I rewrote the code almost completely for PHP7 and to come by the old OpenCV C-interface.
