### ISSUE TITLE
configure: error: 'opencv/objdetect/objdetect_c.h' header not found

### ISSUE THREAD

**Issue by ehitil** [infusion/PHP-Facedetect#25]
i have install the 2.4.5-3.e17 of OpenCV and 2.4.5-3.e17 of OpenCV-devel but i cant complete ./configure ...
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking /usr/include/opencv2/core/core_c.h usability... yes
checking /usr/include/opencv2/core/core_c.h presence... yes
checking for /usr/include/opencv2/core/core_c.h... yes
checking /usr/include/opencv2/imgproc/imgproc_c.h usability... yes
checking /usr/include/opencv2/imgproc/imgproc_c.h presence... yes
checking for /usr/include/opencv2/imgproc/imgproc_c.h... yes
checking /usr/include/opencv2/photo/photo_c.h usability... yes
checking /usr/include/opencv2/photo/photo_c.h presence... yes
checking for /usr/include/opencv2/photo/photo_c.h... yes
checking /usr/include/opencv2/objdetect/objdetect_c.h usability... no
checking /usr/include/opencv2/objdetect/objdetect_c.h presence... no
checking for /usr/include/opencv2/objdetect/objdetect_c.h... no
configure: error: 'opencv/objdetect/objdetect_c.h' header not found

I use centos7

**Comment by arkadicolson** [comment]
I'm having this problem to on Debian

**Comment by asgh** [comment]
On Debian install `libcv-dev` - it should include (via dependencies) everything.

**Comment by arkadicolson** [comment]
I'm still getting the error:
...
checking for /usr/include/opencv2/objdetect/objdetect_c.h... no
configure: error: 'opencv/objdetect/objdetect_c.h' header not found

Clean installed debian jessie
installed libcv-dev and libopencv-dev (with dependencies...)

git clone https://github.com/infusion/PHP-Facedetect.git
phpize
./configure

Any idea's?

**Comment by TheLuckyOne** [comment]
@arkadicolson reinstall openCV :)

**Comment by Grynysh** [comment]
I'm having this problem to on Ubuntu 14. libcv-dev and libopencv-dev installed.

**Comment by ernetas** [comment]
Downloading https://github.com/ernetas/hi-php/blob/latest/objdetect_c.h to `/usr/include/opencv2/objdetect/objdetect_c.h` helps it.

**Comment by infusion** [comment]
Could you guys please test the current master branch? I rewrote the code almost completely for PHP7 and to come by the old OpenCV C-interface.
