### ISSUE TITLE
checking for cvLoad in -lopencv_objdetect... no || configure: error: wrong OpenCV version or OpenCV not found

### ISSUE THREAD

**Issue by kingster** [infusion/PHP-Facedetect#3]
I had installed the latest version from the repository

but yet when i run ./configure i get this error

checking /usr/local/include/opencv/cv.h usability... yes
checking /usr/local/include/opencv/cv.h presence... yes
checking for /usr/local/include/opencv/cv.h... yes
checking /usr/local/include/opencv/highgui.h usability... yes
checking /usr/local/include/opencv/highgui.h presence... yes
checking for /usr/local/include/opencv/highgui.h... yes
checking for cvLoad in -lopencv_objdetect... no
configure: error: wrong OpenCV version or OpenCV not found

Any solutions?

**Comment by infusion** [comment]
Could you guys please test the current master branch? I rewrote the code almost completely for PHP7 and to come by the old OpenCV C-interface.
