### ISSUE TITLE
OpenCV 4.1.2 and PHP-Facedetect

### ISSUE THREAD

**Issue by wellton** [infusion/PHP-Facedetect#34]
Hello. 

this problem is happening. Has anyone managed to make it work? I am using debian testing (pureOS byzantium). on debian buster (pureOS amber) it is 100%. debian testing upgraded from version 3.2 to version 4.1.2 of OpenCV and facedetect broke.

Thanks.

![Captura de tela de 2020-01-28 07-42-53](https://user-images.githubusercontent.com/2234645/73257036-ccd0d680-41a1-11ea-82d4-69f77dcd1f65.png)

**Comment by wellton** [comment]
AEEEEEEEE .... I FIXED IT... FROM BRAZILLL. HuEHuaehuahue
![hue](https://user-images.githubusercontent.com/2234645/73260571-efb2b900-41a8-11ea-8558-6b0e777c3861.png)


its simples:

1) cd PHP-facedetect
2) nano config.m4
3) replace all opencv with opencv4
4) ctrl+o, enter, ctrl+x
5) phpize && ./configure && make && make install 
6) SHOOWW MANN.... Kiss me.

the opencv bastard put 4 at the end. Now pkg-config --cflags --libs opencv just doesn't work. So, pkg-config --cflabs --libs opencv4 works


![Captura de tela de 2020-01-28 08-35-20](https://user-images.githubusercontent.com/2234645/73260818-83848500-41a9-11ea-9672-a6eddfa17a88.png)

**Comment by asgh** [comment]
Please turn this into a pull request.

**Comment by wellton** [comment]
> Please turn this into a pull request.

Done... thanks.
![Captura de tela de 2020-01-28 15-35-24](https://user-images.githubusercontent.com/2234645/73294075-db3fe200-41e3-11ea-8a0a-94da9d99eac9.png)

**Comment by KDederichs** [comment]
Doesn't seem to work with 4.2 though so you might wanna restrict that

**Comment by infusion** [comment]
It should work with opencv up to 4.5 now.
